export default [
  {
    url: "https://www.youtube.com/watch?v=fuhE6PYnRMc",
    title: "Train Vs Giant Pit",
    youtuber: "@MrBeast",
    youtuber_md5: "dd748d5dfc88b91ea388429c3c685874",
    video_url:
      "https://rr3---sn-gqn-cjoz.googlevideo.com/videoplayback?expire=1784824919&ei=9-9hauz1HKjt6dsP76bE-AU&ip=r334fa4c4ec5dd9f5bc8142c5b5a12434&id=o-AIC2q8me7hQmwMVKXvP73s-vWrVsJ4f6Wq0dOu4iHp12&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&cps=715&met=1784803319%2C&mh=9E&mm=31%2C29&mn=sn-gqn-cjoz%2Csn-h5qzen7y&ms=au%2Crdu&mv=m&mvi=3&pl=27&rms=au%2Cau&initcwndbps=4021250&spc=SQ-umnTEMWL-NSslDwi-Lj_ZNhA5jkCU0HI3O3-8L0dhoIjQUPjaCYGg3dQ-v8c-2-aJLA&svpuc=1&ns=WoXKwzSlLcEMK9RXFmiBCqwW&sabr=1&rqh=1&mt=1784803060&fvip=5&keepalive=yes&fexp=51565116%2C51992867&c=WEB&n=SucP6KSMfCM_JfIc&sparams=expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cxpc%2Cspc%2Csvpuc%2Cns%2Csabr%2Crqh&sig=AE0s2JYwRgIhAKvKy59aw4gS58NI6NqEVFXNSLGDMesbcCI_BiJbfvf_AiEAzaNO5I8cDVfJj0vgIqrPzDD6Vu9IV7OY2t07LZZPP_k%3D&lsparams=cps%2Cmet%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRgIhAL-XBRH8MEEkcvVYVpHADelcHhBHeryFWW2DF0tpWwXDAiEA_irVO8MlPERAmtdZSmMBazCIsGT_d3-DACThaucSC1E%3D",
    video_length: 636,
    likes: 6658946,
    views: 305552142,
    date_posted: "2023-07-08T16:00:00.000Z",
    description:
      "Go buy my merch at https://mrbeast.store and if you're looking to set up an online store, it should be on a .Store domain. Thanks for sponsoring this video! ad MrBeastStorePartner\n\n \n\nThank you to Warped Perception for helping with Jet Car https://www.youtube.com/@WarpedPerception\n\n Fireworks provided by https://americanwholesalefireworks.com/ \nand https://www.PyroStarentertainment.com/\n\nSUB TO ALL CHANNELS\nwww.youtube.com/@UCX6OQ3DkcsbYNE6H8uQQuVA\nwww.youtube.com/@UC4-79UOlP48-QNGgCko5p2g \nwww.youtube.com/@UCIPPMRA040LQr5QPyJEbmXA \nwww.youtube.com/@UCUaT_39o1x6qWjz7K2pWcgw \nwww.youtube.com/@UCAiLfjNXkNv24uhpzUgPa6A \nwww.youtube.com/@UCZzvDDvaYti8Dd8bLEiSoyQ \n\nNew Merch - https://mrbeast.store/\nCheck out Viewstats! - https://www.viewstats.com/\n\nFor any questions or inquiries regarding this video, please reach out to chucky@mrbeastbusiness.com\n\nMusic Provided by https://www.extrememusic.com/\n----------------------------------------------------------------\nfollow all of these or i will kick you\n• Facebook - https://www.facebook.com/MrBeast/\n• Twitter - https://twitter.com/MrBeast\n•  Instagram - https://www.instagram.com/mrbeast\n•  Im Hiring! - https://www.mrbeastjobs.com/\n--------------------------------------------------------------------",
    num_comments: 129387,
    subscribers: 509000000,
    video_id: "fuhE6PYnRMc",
    channel_url: "https://www.youtube.com/@MrBeast",
    preview_image: "https://i.ytimg.com/vi_webp/fuhE6PYnRMc/maxresdefault.webp",
    shortcode: "fuhE6PYnRMc",
    verified: true,
    handle_name: "MrBeast",
    avatar_img_channel:
      "https://yt3.ggpht.com/nxYrc_1_2f77DoBadyxMTmv7ZpRZapHR5jbuYe7PlPd5cIRJxtNNEYyOC0ZsxaDyJJzXrnJiuDE=s48-c-k-c0x00ffffff-no-rj",
    is_sponsored: false,
    related_videos: null,
    license: null,
    viewport_frames: "1920x1080 / -",
    current_optimal_res: "1920x1080@30 / 1920x1080@30",
    codecs: "avc1.640028 / mp4a.40.2",
    color: "bt709",
    quality: "hd1080",
    quality_label: "1080p",
    post_type: "post",
    youtuber_id: "UCX6OQ3DkcsbYNE6H8uQQuVA",
    transcript:
      "- I just bought this train and it is currently barreling full-speed towards that giant pit over there. We're also crashing countless cars, blowing up thousands of\nsticks of real dynamite, and even putting 10 jet engines on a car. Just to show you the most\ninsane experiments of all time. Starting with filling a house\nwith over 100,000 fireworks. Please do not try this in your house. For this experiment, each of the boys will hide\na dummy in my new house to see if it's even possible to survive. - Water and fire don't mix, my mannequin is going to survive. - Mine's in the fridge. - Go in, come on. Let's blow this house up. Hey be careful. If you accidentally press\none, the house explodes. - Oh my goodness.\n- Please. Where's your mannequin? - Bathtub.\n- Fridge. - Under the washer. - Tareq?\n- Front porch. - Oh yeah, it's sitting right there. This is gonna be the coolest thing you have ever seen in your life! - Yes! 5, 4, 3, 2, 1. - Fire in the hole! - Oh my God! - What happened to the house? I can't even see it anymore. - Oh my god! - I don't think our mannequins are gonna make it. - The house burned all night, until there was literally nothing left, including all the mannequins. Next experiment. We're about to play Tug-of-War between this real military tank and these two school buses. And the loser gets dragged into the pit. - There's no way the tank loses. - We're probably gonna lose. - No, we're not. - Now obviously, people\ncan't be in these vehicles, 'cause they'll die when\nthey fall in the pit. So this remote actually controls the tank. This feels illegal. 3, 2, 1. Go! - I'm full throttled right now. You're done for! Oh!\n- Oh, we're screwed. - The buses are done for. Oh my god. - Oh my god! - Oh my god! - Do you hear the buses beeping? Its horn's going off. - We're gonna go investigate\nthe bottom of the pit to see the buses. - Oh god.\n- Oh, no. I need to stop looking down this is... Stop moving!\n- I'm not moving! - We're in the pit. Oh my gosh. Bro, look at that. Why'd the bus think it\ncould beat the tank? - I don't think it did. - Later in this video, a train's gonna come off those tracks and land right about there. But before we do that, this is $50,000, and it is surrounded by\nthousands of pounds of TNT. And this is Will. - What's up guys? - See that crate in the field?\n- Yeah. Oh, man. - That is around 1% of the explosives surrounding this money. - Are we safe standing here? - Uh yeah, you'll be fine. Here's my credit card. Spend as much money as you\nwant to protect this 50 grand. I don't care if you use wood, bricks, or even steel to protect this money. Whatever's left of this 50 grand when that TNT blows up, you keep. Good luck building walls. - All right, let's make $50,000! - I don't think he stands a chance. The first thing Will did was buy 12 industrial water containers and filled them with\n20,000 pounds of water. - I'm really worried that Jimmy's TNT is gonna get through this. - And he should be, because this isn't even close\nto enough to stop the TNT. Meanwhile, we're gonna\ntest another experiment. In a previous video, we\nput a jet engine on a car and it jumped eight buses. So this time we put 10\njet engines on the car and we're to see if it\nflies 10 times further. When this car flies off this ramp, I think it's gonna go past\nall the buses into the trees. - I think it's gonna hit the first bus. - Our guesses couldn't be further apart. He's currently matrix-ed into the car, so he sees what the car sees. Chris!\n- Hey! - Oh, should we move? - Yeah, we're sending a rocket car. - Oh, okay. - 3, 2, 1. Send the jet car! The car's coming straight at us. - I lost signal. - Maybe we should jump? - Now I'm straightening it. - Oh, my god! Yeah!\n- What the heck? - Whoa! Wait, wait. We broke the ramp! - I think it was a success.\n- Yes. The jet car easily cleared all 12 buses and literally left a crater in the road. I love how this block of engine's just on the road. - Yeah, it's still smoking. Whoa! - Oh, it's leaking.\n- Oh, and it's smoking. - And now we're back at the giant pit. If you jump in this deep pit and land on a thousand bouncy balls, would you die? - I'd love to know. Nolan, catch! - Catch what? What are we doing? - Goodbye. Oh! Oh. - You completely missed! - Luckily we have more mannequins. Will it survive? Pay attention! - Oh. Oh! - Oh, buckets! - Hey Jimmy! What if we dropped the car in it? - I think you know what's about to happen. - Yo! - Clearly that mannequin didn't survive. Next bit. Meanwhile, Will was desperately trying to protect his $50,000. He's honestly taken\nthis way more seriously than I thought he would. - In the past four days,\nI've hired some professionals and we've already built\nthe cinder block wall, filled it with matches, and we're already on our\nsecond cinder block wall. This dynamite is not getting through. - You blew my expectations\noutta the water. How about this? If you let me double the\nTNT, I'll double the money. - So a hundred grand, double the TNT. - Yeah, but if it blows\nit up, you get nothing. - Take the deal! Take the deal! - Okay! Okay!\n- It's a deal baby! Deal baby! - And while he kept working,\nthe boys and I went bowling. And the bowling balls are these cars. - I'm ready to see some destruction. - Let's see if I get a strike. Hey, first bowl a strike. Oh, it's not going straight. - Oh, it's coming in our direction. We should move. We should move. We should move.\n- Nolan, watch out! - Oh, into the field. There it goes. Oh it's turning around. - Oh, it's coming back! - Oh God.\n- It's coming back. The car's got a mind of it's own! - It's coming back! - Take number two. Oh, that's a perfect strike. - Whoa! - Whoa!\n- Let's go! - I love cars hitting things! - And if you're wondering, the other car is still going in circles. During this bit, me and the boys have been wearing some brand new designs, which you can now buy on our new store, MrBeast.store. 3, 2, 1. We switched from ShopMrBeast.com,\nwhich was very long- - Move over! Move over! - to MrBeast.store. Oh, my gosh! - Ooh!\n- No way! - Whoa! - We just about died. - I'm gonna show you how to\njust hit a full strike easily. - Okay. - All right. Here comes a strike, baby. - A .store domain is the perfect choice for anyone looking to\nsell anything online. - That was the worst throw yet. - That was the best throw yet! - That was awesome! - If you're looking to set up a store, it should be at .store domain, so your customers clearly know\nthat your website is a store. - This is Carl's car. - Unlike .com, MrBeast.store\ntells the world that the website is my store. Oh. Don't forget to head to MrBeast.store and buy our brand new merch, right now. Since I doubled Will's money and TNT, he's completed a seven-layer fortress of 20,000 pounds of water, mattresses, a cinder block wall, four mattresses, a second cinder block wall, an additional 32,000 pounds of water, all packed in with a final wall of dirt. - But I actually have another layer that Jimmy knows nothing about. Jimmy will never see this one coming. - What? - Hey, Jimmy! - How am I supposed to blow up Feastables? - That's the point. - And with the TNT doubled, it's time to put Will's\nbunker to the test. I also brought number 40,\nfrom 1 throughout 100, back to help us blow up all this TNT. You're in charge of the button. Don't press anything yet. Oh god. Moment of truth. Whenever you're ready, press the one. I'm nervous. Whoa! - Oh my god! - Oh, that money's gone for sure. - Oh my god! - Bro, look at that smoke cloud! - I can't even see anything. Is it okay? - Wait, I think I see\nmoney falling from the sky. - No! Seven days of work just went up in flames. I don't know if I've got this. I gotta see if my money's okay! - Why are we running? - I'm running 'cause he's running. - Oh my goodness! Oh, there's so many stacks! - We counted out the money and over $95,000 survived the explosion. - I just won $95,000! - Congrats on the 95 grand. Let's go see what happens if\nyou drive a train into a pit! - Yeah!\n- Whoo! - And now's the moment\nyou've all been waiting for, a train is gonna go\nfull-speed down those tracks into this giant pit. If you were on this train,\nwhere would you sit? - I put my mannequin in the cabin. Statistically the safest\nplace to be on a train. - All right, you got this. - All right, we're gonna\nsit him right on the front. You're not going anywhere. - We're gonna give the\nFeastables bar a front row seat. Stop eating Hershey's. Eat Feastables. We have waited our entire\nlives for this moment. This is going to be epic. Nolan, send the train! - The train's coming! Let's do this! - Oh my god. Here it goes! - Oh my god, here it comes! - Oh, my god! - Whoa! Look at that! That might have been the coolest thing I've ever seen in my life. - Are you kidding me? - Yeah, my mannequin didn't survive. - Train versus pit, the pit won. I hope you enjoyed the video. Let's end it with an explosion. - Ooh! That is so hot! ♪ Mr. Beast ♪",
    formatted_transcript: [
      {
        start_time: 0,
        end_time: 1007,
        duration: 1007,
        text: "- I just bought this train",
      },
      {
        start_time: 1007,
        end_time: 3450,
        duration: 2443,
        text: "and it is currently barreling full-speed",
      },
      {
        start_time: 3450,
        end_time: 5190,
        duration: 1740,
        text: "towards that giant pit over there.",
      },
      {
        start_time: 5190,
        end_time: 7080,
        duration: 1890,
        text: "We're also crashing countless cars,",
      },
      {
        start_time: 7080,
        end_time: 9570,
        duration: 2490,
        text: "blowing up thousands of\nsticks of real dynamite,",
      },
      {
        start_time: 9570,
        end_time: 12150,
        duration: 2580,
        text: "and even putting 10 jet engines on a car.",
      },
      {
        start_time: 12150,
        end_time: 15240,
        duration: 3090,
        text: "Just to show you the most\ninsane experiments of all time.",
      },
      {
        start_time: 15240,
        end_time: 19710,
        duration: 4470,
        text: "Starting with filling a house\nwith over 100,000 fireworks.",
      },
      {
        start_time: 19710,
        end_time: 21900,
        duration: 2190,
        text: "Please do not try this in your house.",
      },
      {
        start_time: 21900,
        end_time: 22980,
        duration: 1080,
        text: "For this experiment,",
      },
      {
        start_time: 22980,
        end_time: 25260,
        duration: 2280,
        text: "each of the boys will hide\na dummy in my new house",
      },
      {
        start_time: 25260,
        end_time: 27510,
        duration: 2250,
        text: "to see if it's even possible to survive.",
      },
      {
        start_time: 27510,
        end_time: 28770,
        duration: 1260,
        text: "- Water and fire don't mix,",
      },
      {
        start_time: 28770,
        end_time: 30210,
        duration: 1440,
        text: "my mannequin is going to survive.",
      },
      {
        start_time: 30210,
        end_time: 32220,
        duration: 2010,
        text: "- Mine's in the fridge.",
      },
      {
        start_time: 32220,
        end_time: 33060,
        duration: 840,
        text: "- Go in, come on.",
      },
      {
        start_time: 33060,
        end_time: 34350,
        duration: 1290,
        text: "Let's blow this house up.",
      },
      {
        start_time: 34350,
        end_time: 35250,
        duration: 900,
        text: "Hey be careful.",
      },
      {
        start_time: 35250,
        end_time: 37980,
        duration: 2730,
        text: "If you accidentally press\none, the house explodes.",
      },
      {
        start_time: 37980,
        end_time: 39210,
        duration: 1230,
        text: "- Oh my goodness.\n- Please.",
      },
      {
        start_time: 39210,
        end_time: 40043,
        duration: 833,
        text: "Where's your mannequin?",
      },
      {
        start_time: 40043,
        end_time: 41220,
        duration: 1177,
        text: "- Bathtub.\n- Fridge.",
      },
      {
        start_time: 41220,
        end_time: 42360,
        duration: 1140,
        text: "- Under the washer.",
      },
      {
        start_time: 42360,
        end_time: 44490,
        duration: 2130,
        text: "- Tareq?\n- Front porch.",
      },
      {
        start_time: 44490,
        end_time: 46530,
        duration: 2040,
        text: "- Oh yeah, it's sitting right there.",
      },
      {
        start_time: 46530,
        end_time: 48090,
        duration: 1560,
        text: "This is gonna be the coolest thing",
      },
      {
        start_time: 48090,
        end_time: 49552,
        duration: 1462,
        text: "you have ever seen in your life!",
      },
      {
        start_time: 49552,
        end_time: 51802,
        duration: 2250,
        text: "- Yes! 5, 4, 3, 2, 1.",
      },
      {
        start_time: 54738,
        end_time: 56321,
        duration: 1583,
        text: "- Fire in the hole!",
      },
      {
        start_time: 59141,
        end_time: 61308,
        duration: 2167,
        text: "- Oh my God!",
      },
      {
        start_time: 64051,
        end_time: 65107,
        duration: 1056,
        text: "- What happened to the house?",
      },
      {
        start_time: 65107,
        end_time: 66507,
        duration: 1400,
        text: "I can't even see it anymore.",
      },
      {
        start_time: 76780,
        end_time: 78234,
        duration: 1454,
        text: "- Oh my god!",
      },
      {
        start_time: 78234,
        end_time: 79067,
        duration: 833,
        text: "- I don't think our mannequins",
      },
      {
        start_time: 79067,
        end_time: 80460,
        duration: 1393,
        text: "are gonna make it.",
      },
      {
        start_time: 80460,
        end_time: 81630,
        duration: 1170,
        text: "- The house burned all night,",
      },
      {
        start_time: 81630,
        end_time: 83880,
        duration: 2250,
        text: "until there was literally nothing left,",
      },
      {
        start_time: 83880,
        end_time: 85620,
        duration: 1740,
        text: "including all the mannequins.",
      },
      {
        start_time: 85620,
        end_time: 87990,
        duration: 2370,
        text: "Next experiment.",
      },
      {
        start_time: 87990,
        end_time: 89220,
        duration: 1230,
        text: "We're about to play Tug-of-War",
      },
      {
        start_time: 89220,
        end_time: 91080,
        duration: 1860,
        text: "between this real military tank",
      },
      {
        start_time: 91080,
        end_time: 92580,
        duration: 1500,
        text: "and these two school buses.",
      },
      {
        start_time: 92580,
        end_time: 94500,
        duration: 1920,
        text: "And the loser gets dragged into the pit.",
      },
      {
        start_time: 94500,
        end_time: 96060,
        duration: 1560,
        text: "- There's no way the tank loses.",
      },
      {
        start_time: 96060,
        end_time: 97080,
        duration: 1020,
        text: "- We're probably gonna lose.",
      },
      {
        start_time: 97080,
        end_time: 97913,
        duration: 833,
        text: "- No, we're not.",
      },
      {
        start_time: 97913,
        end_time: 99720,
        duration: 1807,
        text: "- Now obviously, people\ncan't be in these vehicles,",
      },
      {
        start_time: 99720,
        end_time: 101640,
        duration: 1920,
        text: "'cause they'll die when\nthey fall in the pit.",
      },
      {
        start_time: 101640,
        end_time: 104670,
        duration: 3030,
        text: "So this remote actually controls the tank.",
      },
      {
        start_time: 104670,
        end_time: 105798,
        duration: 1128,
        text: "This feels illegal.",
      },
      {
        start_time: 105798,
        end_time: 106798,
        duration: 1000,
        text: "3, 2, 1. Go!",
      },
      {
        start_time: 111179,
        end_time: 112331,
        duration: 1152,
        text: "- I'm full throttled right now.",
      },
      {
        start_time: 112331,
        end_time: 113303,
        duration: 972,
        text: "You're done for!",
      },
      {
        start_time: 114901,
        end_time: 116610,
        duration: 1709,
        text: "Oh!\n- Oh, we're screwed.",
      },
      {
        start_time: 116610,
        end_time: 117944,
        duration: 1334,
        text: "- The buses are done for.",
      },
      {
        start_time: 117944,
        end_time: 121686,
        duration: 3742,
        text: "Oh my god.",
      },
      {
        start_time: 121686,
        end_time: 123104,
        duration: 1418,
        text: "- Oh my god!",
      },
      {
        start_time: 135234,
        end_time: 136280,
        duration: 1046,
        text: "- Oh my god!",
      },
      {
        start_time: 136280,
        end_time: 138037,
        duration: 1757,
        text: "- Do you hear the buses beeping?",
      },
      {
        start_time: 138037,
        end_time: 139410,
        duration: 1373,
        text: "Its horn's going off.",
      },
      {
        start_time: 139410,
        end_time: 140867,
        duration: 1457,
        text: "- We're gonna go investigate\nthe bottom of the pit",
      },
      {
        start_time: 140867,
        end_time: 142470,
        duration: 1603,
        text: "to see the buses.",
      },
      {
        start_time: 142470,
        end_time: 143850,
        duration: 1380,
        text: "- Oh god.\n- Oh, no.",
      },
      {
        start_time: 143850,
        end_time: 145290,
        duration: 1440,
        text: "I need to stop looking down this is...",
      },
      {
        start_time: 145290,
        end_time: 147780,
        duration: 2490,
        text: "Stop moving!\n- I'm not moving!",
      },
      {
        start_time: 147780,
        end_time: 148620,
        duration: 840,
        text: "- We're in the pit.",
      },
      {
        start_time: 148620,
        end_time: 150540,
        duration: 1920,
        text: "Oh my gosh. Bro, look at that.",
      },
      {
        start_time: 150540,
        end_time: 152413,
        duration: 1873,
        text: "Why'd the bus think it\ncould beat the tank?",
      },
      {
        start_time: 152413,
        end_time: 153360,
        duration: 947,
        text: "- I don't think it did.",
      },
      {
        start_time: 153360,
        end_time: 154410,
        duration: 1050,
        text: "- Later in this video,",
      },
      {
        start_time: 154410,
        end_time: 156360,
        duration: 1950,
        text: "a train's gonna come off those tracks",
      },
      {
        start_time: 156360,
        end_time: 157920,
        duration: 1560,
        text: "and land right about there.",
      },
      {
        start_time: 157920,
        end_time: 161250,
        duration: 3330,
        text: "But before we do that, this is $50,000,",
      },
      {
        start_time: 161250,
        end_time: 164550,
        duration: 3300,
        text: "and it is surrounded by\nthousands of pounds of TNT.",
      },
      {
        start_time: 164550,
        end_time: 166080,
        duration: 1530,
        text: "And this is Will.",
      },
      {
        start_time: 166080,
        end_time: 166913,
        duration: 833,
        text: "- What's up guys?",
      },
      {
        start_time: 166913,
        end_time: 168388,
        duration: 1475,
        text: "- See that crate in the field?\n- Yeah.",
      },
      {
        start_time: 169320,
        end_time: 170490,
        duration: 1170,
        text: "Oh, man.",
      },
      {
        start_time: 170490,
        end_time: 172620,
        duration: 2130,
        text: "- That is around 1% of the explosives",
      },
      {
        start_time: 172620,
        end_time: 173610,
        duration: 990,
        text: "surrounding this money.",
      },
      {
        start_time: 173610,
        end_time: 174690,
        duration: 1080,
        text: "- Are we safe standing here?",
      },
      {
        start_time: 174690,
        end_time: 176430,
        duration: 1740,
        text: "- Uh yeah, you'll be fine.",
      },
      {
        start_time: 176430,
        end_time: 177540,
        duration: 1110,
        text: "Here's my credit card.",
      },
      {
        start_time: 177540,
        end_time: 180510,
        duration: 2970,
        text: "Spend as much money as you\nwant to protect this 50 grand.",
      },
      {
        start_time: 180510,
        end_time: 182310,
        duration: 1800,
        text: "I don't care if you use wood, bricks,",
      },
      {
        start_time: 182310,
        end_time: 184200,
        duration: 1890,
        text: "or even steel to protect this money.",
      },
      {
        start_time: 184200,
        end_time: 185850,
        duration: 1650,
        text: "Whatever's left of this 50 grand",
      },
      {
        start_time: 185850,
        end_time: 187890,
        duration: 2040,
        text: "when that TNT blows up, you keep.",
      },
      {
        start_time: 187890,
        end_time: 188790,
        duration: 900,
        text: "Good luck building walls.",
      },
      {
        start_time: 188790,
        end_time: 190980,
        duration: 2190,
        text: "- All right, let's make $50,000!",
      },
      {
        start_time: 190980,
        end_time: 192690,
        duration: 1710,
        text: "- I don't think he stands a chance.",
      },
      {
        start_time: 192690,
        end_time: 193950,
        duration: 1260,
        text: "The first thing Will did",
      },
      {
        start_time: 193950,
        end_time: 196470,
        duration: 2520,
        text: "was buy 12 industrial water containers",
      },
      {
        start_time: 196470,
        end_time: 198693,
        duration: 2223,
        text: "and filled them with\n20,000 pounds of water.",
      },
      {
        start_time: 200160,
        end_time: 201990,
        duration: 1830,
        text: "- I'm really worried that Jimmy's TNT",
      },
      {
        start_time: 201990,
        end_time: 202980,
        duration: 990,
        text: "is gonna get through this.",
      },
      {
        start_time: 202980,
        end_time: 203850,
        duration: 870,
        text: "- And he should be,",
      },
      {
        start_time: 203850,
        end_time: 207180,
        duration: 3330,
        text: "because this isn't even close\nto enough to stop the TNT.",
      },
      {
        start_time: 207180,
        end_time: 209520,
        duration: 2340,
        text: "Meanwhile, we're gonna\ntest another experiment.",
      },
      {
        start_time: 209520,
        end_time: 212130,
        duration: 2610,
        text: "In a previous video, we\nput a jet engine on a car",
      },
      {
        start_time: 212130,
        end_time: 213990,
        duration: 1860,
        text: "and it jumped eight buses.",
      },
      {
        start_time: 213990,
        end_time: 216600,
        duration: 2610,
        text: "So this time we put 10\njet engines on the car",
      },
      {
        start_time: 216600,
        end_time: 219807,
        duration: 3207,
        text: "and we're to see if it\nflies 10 times further.",
      },
      {
        start_time: 219807,
        end_time: 221190,
        duration: 1383,
        text: "When this car flies off this ramp,",
      },
      {
        start_time: 221190,
        end_time: 223890,
        duration: 2700,
        text: "I think it's gonna go past\nall the buses into the trees.",
      },
      {
        start_time: 223890,
        end_time: 225150,
        duration: 1260,
        text: "- I think it's gonna hit the first bus.",
      },
      {
        start_time: 225150,
        end_time: 227040,
        duration: 1890,
        text: "- Our guesses couldn't be further apart.",
      },
      {
        start_time: 227040,
        end_time: 229620,
        duration: 2580,
        text: "He's currently matrix-ed into the car,",
      },
      {
        start_time: 229620,
        end_time: 231240,
        duration: 1620,
        text: "so he sees what the car sees.",
      },
      {
        start_time: 231240,
        end_time: 232830,
        duration: 1590,
        text: "Chris!\n- Hey!",
      },
      {
        start_time: 232830,
        end_time: 233790,
        duration: 960,
        text: "- Oh, should we move?",
      },
      {
        start_time: 233790,
        end_time: 235685,
        duration: 1895,
        text: "- Yeah, we're sending a rocket car.",
      },
      {
        start_time: 235685,
        end_time: 236518,
        duration: 833,
        text: "- Oh, okay.",
      },
      {
        start_time: 236518,
        end_time: 237351,
        duration: 833,
        text: "- 3, 2, 1.",
      },
      {
        start_time: 239208,
        end_time: 241544,
        duration: 2336,
        text: "Send the jet car!",
      },
      {
        start_time: 244143,
        end_time: 245430,
        duration: 1287,
        text: "The car's coming straight at us.",
      },
      {
        start_time: 245430,
        end_time: 247470,
        duration: 2040,
        text: "- I lost signal.",
      },
      {
        start_time: 247470,
        end_time: 248430,
        duration: 960,
        text: "- Maybe we should jump?",
      },
      {
        start_time: 248430,
        end_time: 250073,
        duration: 1643,
        text: "- Now I'm straightening it.",
      },
      {
        start_time: 258482,
        end_time: 259565,
        duration: 1083,
        text: "- Oh, my god!",
      },
      {
        start_time: 263130,
        end_time: 265250,
        duration: 2120,
        text: "Yeah!\n- What the heck?",
      },
      {
        start_time: 265250,
        end_time: 266120,
        duration: 870,
        text: "- Whoa! Wait, wait.",
      },
      {
        start_time: 266120,
        end_time: 267420,
        duration: 1300,
        text: "We broke the ramp!",
      },
      {
        start_time: 267420,
        end_time: 269010,
        duration: 1590,
        text: "- I think it was a success.\n- Yes.",
      },
      {
        start_time: 269010,
        end_time: 271650,
        duration: 2640,
        text: "The jet car easily cleared all 12 buses",
      },
      {
        start_time: 271650,
        end_time: 274140,
        duration: 2490,
        text: "and literally left a crater in the road.",
      },
      {
        start_time: 274140,
        end_time: 275700,
        duration: 1560,
        text: "I love how this block of engine's",
      },
      {
        start_time: 275700,
        end_time: 276660,
        duration: 960,
        text: "just on the road.",
      },
      {
        start_time: 276660,
        end_time: 277988,
        duration: 1328,
        text: "- Yeah, it's still smoking.",
      },
      {
        start_time: 277988,
        end_time: 278821,
        duration: 833,
        text: "Whoa!",
      },
      {
        start_time: 278821,
        end_time: 280120,
        duration: 1299,
        text: "- Oh, it's leaking.\n- Oh, and it's smoking.",
      },
      {
        start_time: 281070,
        end_time: 283290,
        duration: 2220,
        text: "- And now we're back at the giant pit.",
      },
      {
        start_time: 283290,
        end_time: 284820,
        duration: 1530,
        text: "If you jump in this deep pit",
      },
      {
        start_time: 284820,
        end_time: 286770,
        duration: 1950,
        text: "and land on a thousand bouncy balls,",
      },
      {
        start_time: 286770,
        end_time: 287603,
        duration: 833,
        text: "would you die?",
      },
      {
        start_time: 287603,
        end_time: 289110,
        duration: 1507,
        text: "- I'd love to know. Nolan, catch!",
      },
      {
        start_time: 289110,
        end_time: 290340,
        duration: 1230,
        text: "- Catch what? What are we doing?",
      },
      {
        start_time: 290340,
        end_time: 291173,
        duration: 833,
        text: "- Goodbye.",
      },
      {
        start_time: 293820,
        end_time: 295440,
        duration: 1620,
        text: "Oh!",
      },
      {
        start_time: 295440,
        end_time: 296273,
        duration: 833,
        text: "Oh.",
      },
      {
        start_time: 296273,
        end_time: 297300,
        duration: 1027,
        text: "- You completely missed!",
      },
      {
        start_time: 297300,
        end_time: 298620,
        duration: 1320,
        text: "- Luckily we have more mannequins.",
      },
      {
        start_time: 298620,
        end_time: 299730,
        duration: 1110,
        text: "Will it survive?",
      },
      {
        start_time: 299730,
        end_time: 302753,
        duration: 3023,
        text: "Pay attention!",
      },
      {
        start_time: 304331,
        end_time: 305164,
        duration: 833,
        text: "- Oh. Oh!",
      },
      {
        start_time: 306210,
        end_time: 307440,
        duration: 1230,
        text: "- Oh, buckets!",
      },
      {
        start_time: 307440,
        end_time: 308273,
        duration: 833,
        text: "- Hey Jimmy!",
      },
      {
        start_time: 308273,
        end_time: 309750,
        duration: 1477,
        text: "What if we dropped the car in it?",
      },
      {
        start_time: 309750,
        end_time: 311513,
        duration: 1763,
        text: "- I think you know what's about to happen.",
      },
      {
        start_time: 315558,
        end_time: 319585,
        duration: 4027,
        text: "- Yo!",
      },
      {
        start_time: 323130,
        end_time: 324960,
        duration: 1830,
        text: "- Clearly that mannequin didn't survive.",
      },
      {
        start_time: 324960,
        end_time: 325793,
        duration: 833,
        text: "Next bit.",
      },
      {
        start_time: 325793,
        end_time: 327690,
        duration: 1897,
        text: "Meanwhile, Will was desperately trying",
      },
      {
        start_time: 327690,
        end_time: 329670,
        duration: 1980,
        text: "to protect his $50,000.",
      },
      {
        start_time: 329670,
        end_time: 331770,
        duration: 2100,
        text: "He's honestly taken\nthis way more seriously",
      },
      {
        start_time: 331770,
        end_time: 332640,
        duration: 870,
        text: "than I thought he would.",
      },
      {
        start_time: 332640,
        end_time: 334920,
        duration: 2280,
        text: "- In the past four days,\nI've hired some professionals",
      },
      {
        start_time: 334920,
        end_time: 336840,
        duration: 1920,
        text: "and we've already built\nthe cinder block wall,",
      },
      {
        start_time: 336840,
        end_time: 337860,
        duration: 1020,
        text: "filled it with matches,",
      },
      {
        start_time: 337860,
        end_time: 339840,
        duration: 1980,
        text: "and we're already on our\nsecond cinder block wall.",
      },
      {
        start_time: 339840,
        end_time: 341670,
        duration: 1830,
        text: "This dynamite is not getting through.",
      },
      {
        start_time: 341670,
        end_time: 343920,
        duration: 2250,
        text: "- You blew my expectations\noutta the water.",
      },
      {
        start_time: 343920,
        end_time: 344753,
        duration: 833,
        text: "How about this?",
      },
      {
        start_time: 344753,
        end_time: 347130,
        duration: 2377,
        text: "If you let me double the\nTNT, I'll double the money.",
      },
      {
        start_time: 347130,
        end_time: 349110,
        duration: 1980,
        text: "- So a hundred grand, double the TNT.",
      },
      {
        start_time: 349110,
        end_time: 350765,
        duration: 1655,
        text: "- Yeah, but if it blows\nit up, you get nothing.",
      },
      {
        start_time: 350765,
        end_time: 353190,
        duration: 2425,
        text: "- Take the deal! Take the deal!",
      },
      {
        start_time: 354627,
        end_time: 356010,
        duration: 1383,
        text: "- Okay! Okay!\n- It's a deal baby! Deal baby!",
      },
      {
        start_time: 356010,
        end_time: 358560,
        duration: 2550,
        text: "- And while he kept working,\nthe boys and I went bowling.",
      },
      {
        start_time: 358560,
        end_time: 360690,
        duration: 2130,
        text: "And the bowling balls are these cars.",
      },
      {
        start_time: 360690,
        end_time: 362040,
        duration: 1350,
        text: "- I'm ready to see some destruction.",
      },
      {
        start_time: 362040,
        end_time: 363543,
        duration: 1503,
        text: "- Let's see if I get a strike.",
      },
      {
        start_time: 366480,
        end_time: 368010,
        duration: 1530,
        text: "Hey, first bowl a strike.",
      },
      {
        start_time: 368010,
        end_time: 369540,
        duration: 1530,
        text: "Oh, it's not going straight.",
      },
      {
        start_time: 369540,
        end_time: 370938,
        duration: 1398,
        text: "- Oh, it's coming in our direction.",
      },
      {
        start_time: 373020,
        end_time: 373980,
        duration: 960,
        text: "We should move. We should move.",
      },
      {
        start_time: 373980,
        end_time: 375564,
        duration: 1584,
        text: "We should move.\n- Nolan, watch out!",
      },
      {
        start_time: 376481,
        end_time: 377940,
        duration: 1459,
        text: "- Oh, into the field. There it goes.",
      },
      {
        start_time: 377940,
        end_time: 378960,
        duration: 1020,
        text: "Oh it's turning around.",
      },
      {
        start_time: 378960,
        end_time: 379830,
        duration: 870,
        text: "- Oh, it's coming back!",
      },
      {
        start_time: 379830,
        end_time: 380790,
        duration: 960,
        text: "- Oh God.\n- It's coming back.",
      },
      {
        start_time: 380790,
        end_time: 382290,
        duration: 1500,
        text: "The car's got a mind of it's own!",
      },
      {
        start_time: 382290,
        end_time: 383490,
        duration: 1200,
        text: "- It's coming back!",
      },
      {
        start_time: 383490,
        end_time: 384573,
        duration: 1083,
        text: "- Take number two.",
      },
      {
        start_time: 386160,
        end_time: 387560,
        duration: 1400,
        text: "Oh, that's a perfect strike.",
      },
      {
        start_time: 390566,
        end_time: 391649,
        duration: 1083,
        text: "- Whoa!",
      },
      {
        start_time: 392730,
        end_time: 394290,
        duration: 1560,
        text: "- Whoa!\n- Let's go!",
      },
      {
        start_time: 394290,
        end_time: 395790,
        duration: 1500,
        text: "- I love cars hitting things!",
      },
      {
        start_time: 395790,
        end_time: 396720,
        duration: 930,
        text: "- And if you're wondering,",
      },
      {
        start_time: 396720,
        end_time: 398430,
        duration: 1710,
        text: "the other car is still going in circles.",
      },
      {
        start_time: 398430,
        end_time: 399630,
        duration: 1200,
        text: "During this bit, me and the boys",
      },
      {
        start_time: 399630,
        end_time: 401400,
        duration: 1770,
        text: "have been wearing some brand new designs,",
      },
      {
        start_time: 401400,
        end_time: 402930,
        duration: 1530,
        text: "which you can now buy on our new store,",
      },
      {
        start_time: 402930,
        end_time: 404310,
        duration: 1380,
        text: "MrBeast.store.",
      },
      {
        start_time: 404310,
        end_time: 405143,
        duration: 833,
        text: "3, 2, 1.",
      },
      {
        start_time: 407430,
        end_time: 410400,
        duration: 2970,
        text: "We switched from ShopMrBeast.com,\nwhich was very long-",
      },
      {
        start_time: 410400,
        end_time: 411620,
        duration: 1220,
        text: "- Move over! Move over!",
      },
      {
        start_time: 411620,
        end_time: 412969,
        duration: 1349,
        text: "- to MrBeast.store.",
      },
      {
        start_time: 412969,
        end_time: 414181,
        duration: 1212,
        text: "Oh, my gosh!",
      },
      {
        start_time: 414181,
        end_time: 415900,
        duration: 1719,
        text: "- Ooh!\n- No way!",
      },
      {
        start_time: 415900,
        end_time: 416733,
        duration: 833,
        text: "- Whoa!",
      },
      {
        start_time: 416733,
        end_time: 418140,
        duration: 1407,
        text: "- We just about died.",
      },
      {
        start_time: 418140,
        end_time: 420301,
        duration: 2161,
        text: "- I'm gonna show you how to\njust hit a full strike easily.",
      },
      {
        start_time: 420301,
        end_time: 421134,
        duration: 833,
        text: "- Okay.",
      },
      {
        start_time: 421134,
        end_time: 422548,
        duration: 1414,
        text: "- All right. Here comes a strike, baby.",
      },
      {
        start_time: 422548,
        end_time: 424590,
        duration: 2042,
        text: "- A .store domain is the perfect choice",
      },
      {
        start_time: 424590,
        end_time: 426780,
        duration: 2190,
        text: "for anyone looking to\nsell anything online.",
      },
      {
        start_time: 426780,
        end_time: 428330,
        duration: 1550,
        text: "- That was the worst throw yet.",
      },
      {
        start_time: 430320,
        end_time: 432248,
        duration: 1928,
        text: "- That was the best throw yet!",
      },
      {
        start_time: 432248,
        end_time: 433081,
        duration: 833,
        text: "- That was awesome!",
      },
      {
        start_time: 433081,
        end_time: 434723,
        duration: 1642,
        text: "- If you're looking to set up a store,",
      },
      {
        start_time: 434723,
        end_time: 436440,
        duration: 1717,
        text: "it should be at .store domain,",
      },
      {
        start_time: 436440,
        end_time: 439500,
        duration: 3060,
        text: "so your customers clearly know\nthat your website is a store.",
      },
      {
        start_time: 439500,
        end_time: 440340,
        duration: 840,
        text: "- This is Carl's car.",
      },
      {
        start_time: 440340,
        end_time: 443160,
        duration: 2820,
        text: "- Unlike .com, MrBeast.store\ntells the world",
      },
      {
        start_time: 443160,
        end_time: 444783,
        duration: 1623,
        text: "that the website is my store.",
      },
      {
        start_time: 448080,
        end_time: 448913,
        duration: 833,
        text: "Oh.",
      },
      {
        start_time: 448913,
        end_time: 450600,
        duration: 1687,
        text: "Don't forget to head to MrBeast.store",
      },
      {
        start_time: 450600,
        end_time: 452850,
        duration: 2250,
        text: "and buy our brand new merch, right now.",
      },
      {
        start_time: 452850,
        end_time: 455370,
        duration: 2520,
        text: "Since I doubled Will's money and TNT,",
      },
      {
        start_time: 455370,
        end_time: 457680,
        duration: 2310,
        text: "he's completed a seven-layer fortress",
      },
      {
        start_time: 457680,
        end_time: 461130,
        duration: 3450,
        text: "of 20,000 pounds of water, mattresses,",
      },
      {
        start_time: 461130,
        end_time: 463980,
        duration: 2850,
        text: "a cinder block wall, four mattresses,",
      },
      {
        start_time: 463980,
        end_time: 465810,
        duration: 1830,
        text: "a second cinder block wall,",
      },
      {
        start_time: 465810,
        end_time: 469110,
        duration: 3300,
        text: "an additional 32,000 pounds of water,",
      },
      {
        start_time: 469110,
        end_time: 471930,
        duration: 2820,
        text: "all packed in with a final wall of dirt.",
      },
      {
        start_time: 471930,
        end_time: 473160,
        duration: 1230,
        text: "- But I actually have another layer",
      },
      {
        start_time: 473160,
        end_time: 474480,
        duration: 1320,
        text: "that Jimmy knows nothing about.",
      },
      {
        start_time: 474480,
        end_time: 477870,
        duration: 3390,
        text: "Jimmy will never see this one coming.",
      },
      {
        start_time: 477870,
        end_time: 478950,
        duration: 1080,
        text: "- What?",
      },
      {
        start_time: 478950,
        end_time: 480570,
        duration: 1620,
        text: "- Hey, Jimmy!",
      },
      {
        start_time: 480570,
        end_time: 482580,
        duration: 2010,
        text: "- How am I supposed to blow up Feastables?",
      },
      {
        start_time: 482580,
        end_time: 483660,
        duration: 1080,
        text: "- That's the point.",
      },
      {
        start_time: 483660,
        end_time: 484980,
        duration: 1320,
        text: "- And with the TNT doubled,",
      },
      {
        start_time: 484980,
        end_time: 487170,
        duration: 2190,
        text: "it's time to put Will's\nbunker to the test.",
      },
      {
        start_time: 487170,
        end_time: 489660,
        duration: 2490,
        text: "I also brought number 40,\nfrom 1 throughout 100, back",
      },
      {
        start_time: 489660,
        end_time: 491520,
        duration: 1860,
        text: "to help us blow up all this TNT.",
      },
      {
        start_time: 491520,
        end_time: 492630,
        duration: 1110,
        text: "You're in charge of the button.",
      },
      {
        start_time: 492630,
        end_time: 494479,
        duration: 1849,
        text: "Don't press anything yet.",
      },
      {
        start_time: 494479,
        end_time: 495634,
        duration: 1155,
        text: "Oh god.",
      },
      {
        start_time: 495634,
        end_time: 496467,
        duration: 833,
        text: "Moment of truth.",
      },
      {
        start_time: 496467,
        end_time: 499050,
        duration: 2583,
        text: "Whenever you're ready, press the one.",
      },
      {
        start_time: 499050,
        end_time: 500874,
        duration: 1824,
        text: "I'm nervous.",
      },
      {
        start_time: 502183,
        end_time: 504143,
        duration: 1960,
        text: "Whoa!",
      },
      {
        start_time: 507600,
        end_time: 509310,
        duration: 1710,
        text: "- Oh my god!",
      },
      {
        start_time: 509310,
        end_time: 511246,
        duration: 1936,
        text: "- Oh, that money's gone for sure.",
      },
      {
        start_time: 515910,
        end_time: 516743,
        duration: 833,
        text: "- Oh my god!",
      },
      {
        start_time: 516743,
        end_time: 518250,
        duration: 1507,
        text: "- Bro, look at that smoke cloud!",
      },
      {
        start_time: 518250,
        end_time: 520350,
        duration: 2100,
        text: "- I can't even see anything. Is it okay?",
      },
      {
        start_time: 520350,
        end_time: 522468,
        duration: 2118,
        text: "- Wait, I think I see\nmoney falling from the sky.",
      },
      {
        start_time: 522468,
        end_time: 523301,
        duration: 833,
        text: "- No!",
      },
      {
        start_time: 523301,
        end_time: 525480,
        duration: 2179,
        text: "Seven days of work just went up in flames.",
      },
      {
        start_time: 525480,
        end_time: 527100,
        duration: 1620,
        text: "I don't know if I've got this.",
      },
      {
        start_time: 527100,
        end_time: 529170,
        duration: 2070,
        text: "I gotta see if my money's okay!",
      },
      {
        start_time: 529170,
        end_time: 530130,
        duration: 960,
        text: "- Why are we running?",
      },
      {
        start_time: 530130,
        end_time: 531734,
        duration: 1604,
        text: "- I'm running 'cause he's running.",
      },
      {
        start_time: 533400,
        end_time: 534570,
        duration: 1170,
        text: "- Oh my goodness!",
      },
      {
        start_time: 534570,
        end_time: 535830,
        duration: 1260,
        text: "Oh, there's so many stacks!",
      },
      {
        start_time: 535830,
        end_time: 536790,
        duration: 960,
        text: "- We counted out the money",
      },
      {
        start_time: 536790,
        end_time: 539619,
        duration: 2829,
        text: "and over $95,000 survived the explosion.",
      },
      {
        start_time: 539619,
        end_time: 541797,
        duration: 2178,
        text: "- I just won $95,000!",
      },
      {
        start_time: 541797,
        end_time: 543330,
        duration: 1533,
        text: "- Congrats on the 95 grand.",
      },
      {
        start_time: 543330,
        end_time: 546420,
        duration: 3090,
        text: "Let's go see what happens if\nyou drive a train into a pit!",
      },
      {
        start_time: 546420,
        end_time: 547623,
        duration: 1203,
        text: "- Yeah!\n- Whoo!",
      },
      {
        start_time: 548820,
        end_time: 550950,
        duration: 2130,
        text: "- And now's the moment\nyou've all been waiting for,",
      },
      {
        start_time: 550950,
        end_time: 553710,
        duration: 2760,
        text: "a train is gonna go\nfull-speed down those tracks",
      },
      {
        start_time: 553710,
        end_time: 555090,
        duration: 1380,
        text: "into this giant pit.",
      },
      {
        start_time: 555090,
        end_time: 557130,
        duration: 2040,
        text: "If you were on this train,\nwhere would you sit?",
      },
      {
        start_time: 557130,
        end_time: 558360,
        duration: 1230,
        text: "- I put my mannequin in the cabin.",
      },
      {
        start_time: 558360,
        end_time: 560160,
        duration: 1800,
        text: "Statistically the safest\nplace to be on a train.",
      },
      {
        start_time: 560160,
        end_time: 561889,
        duration: 1729,
        text: "- All right, you got this.",
      },
      {
        start_time: 561889,
        end_time: 563777,
        duration: 1888,
        text: "- All right, we're gonna\nsit him right on the front.",
      },
      {
        start_time: 565560,
        end_time: 566393,
        duration: 833,
        text: "You're not going anywhere.",
      },
      {
        start_time: 566393,
        end_time: 568560,
        duration: 2167,
        text: "- We're gonna give the\nFeastables bar a front row seat.",
      },
      {
        start_time: 568560,
        end_time: 570420,
        duration: 1860,
        text: "Stop eating Hershey's. Eat Feastables.",
      },
      {
        start_time: 570420,
        end_time: 572550,
        duration: 2130,
        text: "We have waited our entire\nlives for this moment.",
      },
      {
        start_time: 572550,
        end_time: 573817,
        duration: 1267,
        text: "This is going to be epic.",
      },
      {
        start_time: 573817,
        end_time: 575517,
        duration: 1700,
        text: "Nolan, send the train!",
      },
      {
        start_time: 575517,
        end_time: 577020,
        duration: 1503,
        text: "- The train's coming!",
      },
      {
        start_time: 577020,
        end_time: 578859,
        duration: 1839,
        text: "Let's do this!",
      },
      {
        start_time: 583340,
        end_time: 586630,
        duration: 3290,
        text: "- Oh my god. Here it goes!",
      },
      {
        start_time: 588359,
        end_time: 591776,
        duration: 3417,
        text: "- Oh my god, here it comes!",
      },
      {
        start_time: 596139,
        end_time: 597851,
        duration: 1712,
        text: "- Oh, my god!",
      },
      {
        start_time: 604931,
        end_time: 609931,
        duration: 5000,
        text: "- Whoa! Look at that!",
      },
      {
        start_time: 614760,
        end_time: 616140,
        duration: 1380,
        text: "That might have been the coolest thing",
      },
      {
        start_time: 616140,
        end_time: 617235,
        duration: 1095,
        text: "I've ever seen in my life.",
      },
      {
        start_time: 617235,
        end_time: 618720,
        duration: 1485,
        text: "- Are you kidding me?",
      },
      {
        start_time: 618720,
        end_time: 620010,
        duration: 1290,
        text: "- Yeah, my mannequin didn't survive.",
      },
      {
        start_time: 620010,
        end_time: 621900,
        duration: 1890,
        text: "- Train versus pit, the pit won.",
      },
      {
        start_time: 621900,
        end_time: 623280,
        duration: 1380,
        text: "I hope you enjoyed the video.",
      },
      {
        start_time: 623280,
        end_time: 624830,
        duration: 1550,
        text: "Let's end it with an explosion.",
      },
      {
        start_time: 626460,
        end_time: 628147,
        duration: 1687,
        text: "- Ooh!",
      },
      {
        start_time: 628147,
        end_time: 629357,
        duration: 1210,
        text: "That is so hot!",
      },
      {
        start_time: 631008,
        end_time: 633341,
        duration: 2333,
        text: "♪ Mr. Beast ♪",
      },
    ],
    hashtags: null,
    tags: [],
    next_recommended_videos: [
      {
        url: "https://www.youtube.com/watch?v=iYlODtkyw_I",
        title: "Survive 30 Days Chained To A Stranger, Win $250,000, video",
        thumbnail: "https://i.ytimg.com/vi_webp/iYlODtkyw_I/maxresdefault.webp",
        startMs: 630668,
        endMs: 635668,
        style: "VIDEO",
      },
    ],
    recommended_videos: [
      {
        url: "https://www.youtube.com/watch?v=vBpQ1SlfVtU&pp=ugUEEgJlbg%3D%3D",
        title: "World’s Largest Dominoes Vs Store",
        thumbnail:
          "https://i.ytimg.com/vi/vBpQ1SlfVtU/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDkNxsNN-85eOFYE-YSVrIy0VztcA",
      },
      {
        url: "https://www.youtube.com/watch?v=7ESeQBeikKs&pp=ugUEEgJlbg%3D%3D",
        title: "Protect $500,000 Keep It!",
        thumbnail:
          "https://i.ytimg.com/vi/7ESeQBeikKs/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBl8obk30BdrdjzNugamL1DwRtE1A",
      },
      {
        url: "https://www.youtube.com/watch?v=SDhUit9B9ag",
        title: "War robots f2p ",
        thumbnail:
          "https://i.ytimg.com/vi/SDhUit9B9ag/hqdefault.jpg?sqp=-oaymwFBCNACELwBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGF0gXShdMA8=&rs=AOn4CLBRyOmid0Bf70Cu_noZReAwbSl3ZA",
      },
      {
        url: "https://www.youtube.com/watch?v=ZRjgy6RAupY&pp=ugUEEgJlbg%3D%3D",
        title: "Hydraulic Press vs 1000 Sheets Of Paper",
        thumbnail:
          "https://i.ytimg.com/vi/ZRjgy6RAupY/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDssf6j6HN_uK0cXQEH_SjdsFMNDw",
      },
      {
        url: "https://www.youtube.com/watch?v=eRVxRuHPVaI&pp=ugUEEgJlbg%3D%3D",
        title: "I built a LEGO TRAIN around MY HOUSE...",
        thumbnail:
          "https://i.ytimg.com/vi/eRVxRuHPVaI/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBgbwwMRocnGRl3x--_cDagg_YEEw",
      },
      {
        url: "https://www.youtube.com/watch?v=h5NvTTOlOtI&pp=ugUEEgJlbg%3D%3D",
        title: "Real Life Spider-Man Vs Skyscraper",
        thumbnail:
          "https://i.ytimg.com/vi/h5NvTTOlOtI/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDaG_KeOs500IRaZic8_1n98LYs1A",
      },
      {
        url: "https://www.youtube.com/watch?v=PWirijQkH4M&pp=ugUHEgVlbi1VUw%3D%3D",
        title: "World’s Deadliest Obstacle Course!",
        thumbnail:
          "https://i.ytimg.com/vi/PWirijQkH4M/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDPHqpUv2ZtW_duV3DkaLxx5lAk1g",
      },
      {
        url: "https://www.youtube.com/watch?v=_AbFXuGDRTs&pp=ugUEEgJlbtIHCQmjCwGHKiGM7w%3D%3D",
        title: "$1 vs $1,000,000,000 Nuclear Bunker!",
        thumbnail:
          "https://i.ytimg.com/vi/_AbFXuGDRTs/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAfdNSZX56X0xY_Qk1XoyVj7AgSig",
      },
      {
        url: "https://www.youtube.com/watch?v=mKdjycj-7eE&pp=ugUEEgJlbg%3D%3D",
        title: "Stop This Train, Win a Lamborghini",
        thumbnail:
          "https://i.ytimg.com/vi/mKdjycj-7eE/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDk-5bUzWPitCr0TNOpMcz_zc3RBQ",
      },
      {
        url: "https://www.youtube.com/watch?v=48h57PspBec&pp=ugUEEgJlbg%3D%3D",
        title: "$1 vs $1,000,000,000 Yacht!",
        thumbnail:
          "https://i.ytimg.com/vi/48h57PspBec/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC9aeHmLk1NrVk_IlTDguXPy2-wsw",
      },
      {
        url: "https://www.youtube.com/watch?v=ICNtItWYMNE&pp=ugUEEgJlbg%3D%3D",
        title: "World's Deadliest Explosion!",
        thumbnail:
          "https://i.ytimg.com/vi/ICNtItWYMNE/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBjw-oo42wEUpwFNJORLJN4IQks1Q",
      },
      {
        url: "https://www.youtube.com/watch?v=GLoeAJUcz38&pp=ugUEEgJlbtIHCQmjCwGHKiGM7w%3D%3D",
        title: "Press This Button To Win $100,000!",
        thumbnail:
          "https://i.ytimg.com/vi/GLoeAJUcz38/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAwymgBzExID0DbyQwhwgQ5H_0BzA",
      },
    ],
    transcript_language: [
      {
        language: "Arabic",
        auto_translate: false,
      },
      {
        language: "Chinese (Simplified)",
        auto_translate: false,
      },
      {
        language: "Chinese (Traditional)",
        auto_translate: false,
      },
      {
        language: "English",
        auto_translate: false,
      },
      {
        language: "English (auto-generated)",
        auto_translate: true,
      },
      {
        language: "French",
        auto_translate: false,
      },
      {
        language: "German",
        auto_translate: false,
      },
      {
        language: "Hindi",
        auto_translate: false,
      },
      {
        language: "Italian",
        auto_translate: false,
      },
      {
        language: "Japanese",
        auto_translate: false,
      },
      {
        language: "Korean",
        auto_translate: false,
      },
      {
        language: "Persian",
        auto_translate: false,
      },
      {
        language: "Polish",
        auto_translate: false,
      },
      {
        language: "Portuguese",
        auto_translate: false,
      },
      {
        language: "Russian",
        auto_translate: false,
      },
      {
        language: "Spanish",
        auto_translate: false,
      },
      {
        language: "Turkish",
        auto_translate: false,
      },
      {
        language: "Uzbek",
        auto_translate: false,
      },
      {
        language: "Vietnamese",
        auto_translate: false,
      },
    ],
    chapters: null,
    transcription_language: null,
    is_age_restricted: false,
    channel_url_decoded: "https://www.youtube.com/@MrBeast",
    category: "Entertainment",
    audio_tracks: [
      {
        audio_track_language_id: "ar",
        audio_track_language: "Arabic",
      },
      {
        audio_track_language_id: "bn",
        audio_track_language: "Bangla",
      },
      {
        audio_track_language_id: "de",
        audio_track_language: "German",
      },
      {
        audio_track_language_id: "es",
        audio_track_language: "Spanish",
      },
      {
        audio_track_language_id: "fa",
        audio_track_language: "Persian",
      },
      {
        audio_track_language_id: "fr",
        audio_track_language: "French",
      },
      {
        audio_track_language_id: "hi",
        audio_track_language: "Hindi",
      },
      {
        audio_track_language_id: "id",
        audio_track_language: "Indonesian",
      },
      {
        audio_track_language_id: "it",
        audio_track_language: "Italian",
      },
      {
        audio_track_language_id: "ja",
        audio_track_language: "Japanese",
      },
      {
        audio_track_language_id: "ko",
        audio_track_language: "Korean",
      },
      {
        audio_track_language_id: "ml",
        audio_track_language: "Malayalam",
      },
      {
        audio_track_language_id: "mr",
        audio_track_language: "Marathi",
      },
      {
        audio_track_language_id: "pa",
        audio_track_language: "Punjabi",
      },
      {
        audio_track_language_id: "pl",
        audio_track_language: "Polish",
      },
      {
        audio_track_language_id: "pt",
        audio_track_language: "Portuguese",
      },
      {
        audio_track_language_id: "ru",
        audio_track_language: "Russian",
      },
      {
        audio_track_language_id: "ta",
        audio_track_language: "Tamil",
      },
      {
        audio_track_language_id: "te",
        audio_track_language: "Telugu",
      },
      {
        audio_track_language_id: "th",
        audio_track_language: "Thai",
      },
      {
        audio_track_language_id: "tr",
        audio_track_language: "Turkish",
      },
      {
        audio_track_language_id: "uz",
        audio_track_language: "Uzbek",
      },
      {
        audio_track_language_id: "vi",
        audio_track_language: "Vietnamese",
      },
      {
        audio_track_language_id: "zh-Hans",
        audio_track_language: "Chinese (Simplified)",
      },
      {
        audio_track_language_id: "zh-Hant",
        audio_track_language: "Chinese (Traditional)",
      },
      {
        audio_track_language_id: "en",
        audio_track_language: "English original",
      },
    ],
    made_for_kids: false,
    player_notification_text: null,
    ai_content_label: true,
    timestamp: "2026-07-23T10:43:55.312Z",
    input: {
      url: "https://www.youtube.com/watch?v=fuhE6PYnRMc",
      country: "",
      transcription_language: "",
    },
  },
];
